create sequence hibernate_sequence start 1 increment 1;
create table photo_results (id int8 not null, description varchar(255), filename varchar(255), tutorial_id int8, user_id int8, primary key (id));
create table tutorials (id int8 generated by default as identity, content text, created_on timestamp, img_name varchar(255), title varchar(255), updated_on timestamp, user_id int8, primary key (id));
create table user_roles (user_id int8 not null, user_roles varchar(255));
create table users (id int8 not null, active boolean not null, password varchar(255), username varchar(255), primary key (id));
alter table if exists photo_results add constraint FKq6nsjerran476korin0ybheku foreign key (tutorial_id) references tutorials on delete cascade;
alter table if exists photo_results add constraint FK5heumtxculqck90kbp2mtufgx foreign key (user_id) references users on delete cascade;
alter table if exists tutorials add constraint FKhxjckit58h68yl9ysd84vyf0y foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;

